global:
  imagePullPolicy: Always
  vault:
    name: sausage-store-vault
    host: ""
    scheme: http
    port: "8200"
    vaultToken: ""

environment: production

frontend:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-norammoranos.2sem.students-projects.ru
    path: /
    pathType: Prefix
    tlsSecretName: 2sem-students-projects-wildcard-secret
  containerPort: 80
  image: noranori/sausage-frontend:latest
  resources:
    requests:
      memory: "96Mi"
      cpu: "100m"
    limits:
      memory: "192Mi"
      cpu: "250m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  image: noranori/sausage-backend:latest
  resources:
    requests:
      memory: "192Mi"
      cpu: "150m"
    limits:
      memory: "384Mi"
      cpu: "500m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5
  vpa:
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: backend
          controlledResources:
            - cpu
            - memory

backend-report:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  image: noranori/sausage-backend-report:latest
  service:
    port: 8080
  containerPort: 8080
  config:
    port: "8080"
  secret:
    db: mongodb://reports:reportspassword@mongodb:27017/sausage-store
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75

infra:
  postgresql:
    image: postgres:15-alpine
    database: sausage-store
    username: store
    password: storepassword
    containerPort: 5432
    storage: 1Gi
    resources:
      requests:
        memory: "192Mi"
        cpu: "200m"
      limits:
        memory: "384Mi"
        cpu: "500m"
  mongodb:
    image: mongo:7.0
    rootUsername: root
    rootPassword: rootpassword
    appDatabase: sausage-store
    appUsername: reports
    appPassword: reportspassword
    containerPort: 27017
    storage: 1Gi
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    initJob:
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "250m"
